version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on: 
      mongoservice:
        condition: service_started
    links: 
      - mongoservice
  mongoservice:
    container_name: mongoservice
    image: mongo:6.0.5
    user: "1001:1001"
    volumes:
      - /var/db/mongo/data:/data/db:Z
    ports:
      - "27017:27017"