version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on: 
      - mongoservice
    links: 
      - mongoservice
    command: [ "./scripts/wait-for-it.sh", "mongoservice:27017", "--", "npm", "start" ]
  mongoservice:
    container_name: mongoservice
    image: mongo:6.0.5
    volumes:
      - /Users/strs/Documents/mongodata:/data/db
    ports:
      - "37017:27017"